export default [
  { src: '/images/android-brands.svg' },
  // { src: '/images/apollo-brands.svg' },
  { src: '/images/aws-brands.svg' },
  { src: '/images/app-store-brands.svg' },
  // { src: '/images/babel-brands.svg' },
  { src: '/images/css3-alt-brands.svg' },
  { src: '/images/chakra-brands.svg' },
  { src: '/images/docker-brands.svg' },
  // { src: '/images/eslint-brands.svg' },
  // { src: '/images/flow-brands.svg' },
  { src: '/images/github-brands.svg' },
  { src: '/images/google-play-brands.svg' },
  { src: '/images/graphql-brands.svg' },
  {
    src: '/images/hapi.svg',
    width: 1000,
    height: 700,
  },
  { src: '/images/html5-brands.svg' },
  { src: '/images/jest-brands.svg' },
  { src: '/images/less-brands.svg' },
  // { src: '/images/lodash-brands.svg' },
  // { src: '/images/material-brands.svg' },
  {
    src: '/images/mongodb.svg',
    width: 1000,
    height: 250,
  },
  {
    src: '/images/nextjs-brands.svg',
    width: 148,
    height: 90,
  },
  // { src: '/images/node-brands.svg' },
  { src: '/images/node-js-brands.svg' },
  // { src: '/images/php-brands.svg' },
  // { src: '/images/redux-brands.svg' },
  { src: '/images/react-brands.svg' },
  { src: '/images/ts-brands.svg' },
  { src: '/images/sass-brands.svg' },
  { src: '/images/storybook-brands.svg' },
  // { src: '/images/ubuntu-brands.svg' },
  // { src: '/images/vscode-brands.svg' },
  // {
  //   src: '/images/webpack-brands.svg',
  //   width: 3046.7,
  //   height: 875.7,
  // },
  // { src: '/images/xd-brands.svg' },
  { src: '/images/yarn-brands.svg' },
]
